# Generated by Django 4.0 on 2022-08-09 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account', serialize=False, to='auth.user')),
                ('has_scrapbook', models.BooleanField()),
                ('shares_scrapbook', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('uploads', models.FileField(blank=True, upload_to='activity_uploads')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('vid_src', models.CharField(blank=True, max_length=22)),
                ('song_embed', models.CharField(blank=True, max_length=24)),
                ('video_file', models.FileField(blank=True, upload_to='page_videos')),
                ('image_file', models.FileField(blank=True, upload_to='page_images')),
                ('title_slug', models.SlugField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='scrapbook.account')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio', models.FileField(blank=True, upload_to='page_audio_files')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapbook.account')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapbook.page')),
            ],
        ),
        migrations.CreateModel(
            name='TextNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000)),
                ('title', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapbook.account')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapbook.page')),
            ],
        ),
        migrations.CreateModel(
            name='Scrapbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(max_length=20)),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborators', to='scrapbook.Account')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='scrapbook.account')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='scrapbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapbook.scrapbook'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, upload_to='page_images')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapbook.page')),
                ('uploaded_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scrapbook.account')),
            ],
        ),
    ]
