# Generated by Django 4.0 on 2022-07-25 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapbook',
            name='owner',
        ),
        migrations.AlterField(
            model_name='scrapbook',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
