# Generated by Django 4.0 on 2022-08-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0002_alter_account_has_scrapbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.IntegerField(default=4321),
            preserve_default=False,
        ),
    ]
