# Generated by Django 4.0 on 2022-07-25 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('scrapbook', '0002_remove_scrapbook_owner_alter_scrapbook_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapbook',
            name='owner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='auth.user'),
            preserve_default=False,
        ),
    ]
