# Generated by Django 4.0 on 2022-07-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0003_scrapbook_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
