# Generated by Django 4.0 on 2022-08-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0003_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='recovery_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
