# Generated by Django 4.0 on 2022-07-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0004_remove_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='vid_id',
            field=models.CharField(blank=True, max_length=22),
        ),
    ]
