# Generated by Django 4.0 on 2022-08-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0005_alter_scrapbook_collaborators_alter_scrapbook_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='recovery_relationship',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
