# Generated by Django 4.0 on 2022-08-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0006_rename_song_id_page_song_embed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='vid_id',
            new_name='vid_src',
        ),
    ]
