# Generated by Django 4.0 on 2022-08-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0008_page_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='video_url',
        ),
    ]
