# Generated by Django 4.0 on 2022-08-04 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapbook', '0009_remove_page_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title_slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='scrapbook',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborates_on', to=settings.AUTH_USER_MODEL),
        ),
    ]
