# Generated by Django 4.0 on 2022-08-05 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapbook', '0010_alter_page_title_slug_alter_scrapbook_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapbook',
            name='collaborators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
