# Generated by Django 4.0 on 2022-08-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapbook', '0011_alter_scrapbook_collaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textnote',
            name='title',
        ),
    ]
