# Generated by Django 4.0 on 2022-08-08 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapbook', '0013_textnote_title_alter_textnote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapbook',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
